/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dell_client5_led */

#ifndef _Included_com_example_dell_client5_led
#define _Included_com_example_dell_client5_led
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dell_client5_led
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_dell_client5_led_Open
  (JNIEnv *, jobject);

/*
 * Class:     com_example_dell_client5_led
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_dell_client5_led_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_dell_client5_led
 * Method:    Ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_dell_client5_led_Ioctl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
